name: fb4
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Nidal-Bakir/FP

environment:
  sdk: ^3.1.0

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
